name: All
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  style-and-lint:
    name: Style and lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: Style and lint
        run: ./scripts/ci.py style_and_lint
  macos-build:
    name: Build for macOS
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7
      - name: Build
        id: build
        run: |
          ./scripts/ci.py build \
            --codesign-application-identity "${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}" \
            --codesign-installer-identity "${{ secrets.MACOS_SIGNING_INSTALLER_IDENTITY }}" \
            --codesign-certificate "${{ secrets.MACOS_SIGNING_CERT }}" \
            --codesign-certificate-password "${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}" \
            --notarization-user "${{ secrets.MACOS_NOTARIZATION_USERNAME }}" \
            --notarization-password "${{ secrets.MACOS_NOTARIZATION_PASSWORD }}"
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.name }}-${{ steps.build.outputs.version }}-macos-universal
          path: ${{ github.workspace }}/release/*-macos-universal.*
      - name: Upload Debug Symbol Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.name }}-${{ steps.build.outputs.version }}-macos-universal-dSYMs
          path: ${{ github.workspace }}/release/*-macos-universal-dSYMs.*
  ubuntu-build:
    name: Build for Ubuntu
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - name: Build
        id: build
        run: ./scripts/ci.py build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.name }}-${{ steps.build.outputs.version }}-ubuntu-24.04-x86_64
          path: |
            ${{ github.workspace }}/release/*-x86_64-linux-gnu.*
            ${{ github.workspace }}/release/*-source.*
  windows-build:
    name: Build for Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v7
      - name: Build
        id: build
        shell: pwsh
        run: python scripts/ci.py build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.build.outputs.name }}-${{ steps.build.outputs.version }}-windows-x64
          path: ${{ github.workspace }}/release/*-windows-x64*.*
  create-release:
    name: Create Release
    if: github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    needs: [style-and-lint, macos-build, ubuntu-build, windows-build]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
      - name: Collect Release Assets
        id: assets
        run: ./scripts/ci.py release
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          draft: false
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.assets.outputs.displayName }} ${{ github.ref_name }}
          files: |
            ${{ github.workspace }}/*.exe
            ${{ github.workspace }}/*.zip
            ${{ github.workspace }}/*.pkg
            ${{ github.workspace }}/*.deb
            ${{ github.workspace }}/*.tar.xz
