name: Build
run-name: ${{ github.event.pull_request.title || github.ref_name }} run 🚀
on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
    branches: [master, main]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - main
      - 'release/**'
    tags:
      - '*'
permissions:
  contents: read
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true
jobs:
  rustfmt:
    name: Check Formatting 🔍
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Up Rust 🦀
        run: python3 .github/scripts/setup_rust.py
      - name: rustfmt check 🦀
        run: cargo fmt --check
  clippy:
    name: Check Lints 🔍
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Up Environment 🔧
        run: python3 .github/scripts/setup_env.py
      - name: Set Up Rust 🦀
        run: python3 .github/scripts/setup_rust.py
      - name: clippy check 🦀
        run: cargo clippy --all-targets -- --deny warnings
  check-event:
    name: Check GitHub Event Data 🔎
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    outputs:
      package: ${{ steps.setup.outputs.package }}
      codesign: ${{ steps.setup.outputs.codesign }}
      notarize: ${{ steps.setup.outputs.notarize }}
      commitHash: ${{ steps.setup.outputs.commitHash }}
      pluginName: ${{ steps.setup.outputs.pluginName }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check Event Data ☑️
        id: setup
        env:
          GH_TOKEN: ${{ github.token }}
        run: python3 .github/scripts/check_event.py
  macos-build:
    name: Build for macOS 🍏
    runs-on: macos-26
    needs: check-event
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set Up Environment 🔧
        id: setup
        run: python3 .github/scripts/setup_env.py
      - name: Set Up Rust 🦀
        run: python3 .github/scripts/setup_rust.py
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            ${{ github.workspace }}/target
          key: ${{ runner.os }}-macos-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-macos-cargo-
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.deps
          key: ${{ runner.os }}-macos-deps-${{ hashFiles('buildspec.json') }}
      - name: Set Up Codesigning 🔑
        if: fromJSON(needs.check-event.outputs.codesign)
        id: codesign
        env:
          MACOS_SIGNING_IDENTITY: ${{ secrets.MACOS_SIGNING_APPLICATION_IDENTITY }}
          MACOS_SIGNING_IDENTITY_INSTALLER: ${{ secrets.MACOS_SIGNING_INSTALLER_IDENTITY }}
          MACOS_SIGNING_CERT: ${{ secrets.MACOS_SIGNING_CERT }}
          MACOS_SIGNING_CERT_PASSWORD: ${{ secrets.MACOS_SIGNING_CERT_PASSWORD }}
          MACOS_KEYCHAIN_PASSWORD: ${{ secrets.MACOS_KEYCHAIN_PASSWORD }}
          MACOS_SIGNING_PROVISIONING_PROFILE: ${{ secrets.MACOS_SIGNING_PROVISIONING_PROFILE }}
          MACOS_NOTARIZATION_USERNAME: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
          MACOS_NOTARIZATION_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
        run: python3 .github/scripts/setup_codesigning.py
      - name: Build Plugin 🧱
        env:
          HAVE_CODESIGN_IDENT: ${{ steps.codesign.outputs.haveCodesignIdent }}
          CODESIGN_IDENT: ${{ steps.codesign.outputs.codesignIdent }}
          CODESIGN_TEAM: ${{ steps.codesign.outputs.codesignTeam }}
        run: python3 .github/scripts/build_plugin.py
      - name: Verify Universal Binary 🔍
        run: python3 .github/scripts/verify_universal_binary.py
      - name: Package Plugin 📀
        env:
          PACKAGE: ${{ needs.check-event.outputs.package }}
          NOTARIZE: ${{ needs.check-event.outputs.notarize }}
          HAVE_CODESIGN_IDENT: ${{ steps.codesign.outputs.haveCodesignIdent }}
          HAVE_NOTARIZATION_USER: ${{ steps.codesign.outputs.haveNotarizationUser }}
          CODESIGN_IDENT: ${{ steps.codesign.outputs.codesignIdent }}
          CODESIGN_IDENT_INSTALLER: ${{ steps.codesign.outputs.installerIdent }}
          CODESIGN_TEAM: ${{ steps.codesign.outputs.codesignTeam }}
          CODESIGN_IDENT_USER: ${{ secrets.MACOS_NOTARIZATION_USERNAME }}
          CODESIGN_IDENT_PASS: ${{ secrets.MACOS_NOTARIZATION_PASSWORD }}
        run: python3 .github/scripts/package_plugin.py
      - name: Upload Artifacts 📡
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-macos-universal-${{ needs.check-event.outputs.commitHash }}
          path: ${{ github.workspace }}/release/${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-macos-universal.*
      - name: Upload Debug Symbol Artifacts 🪲
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-macos-universal-${{ needs.check-event.outputs.commitHash }}-dSYMs
          path: ${{ github.workspace }}/release/${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-macos-universal-dSYMs.*
  ubuntu-build:
    name: Build for Ubuntu 🐧
    strategy:
      matrix:
        os: [ubuntu-24.04]
    runs-on: ${{ matrix.os }}
    needs: check-event
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set Up Environment 🔧
        id: setup
        run: python3 .github/scripts/setup_env.py
      - name: Set Up Rust 🦀
        run: python3 .github/scripts/setup_rust.py
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            ${{ github.workspace }}/target
          key: ${{ runner.os }}-ubuntu-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-ubuntu-cargo-
      - name: Build Plugin 🧱
        run: python3 .github/scripts/build_plugin.py
      - name: Package Plugin 📀
        env:
          PACKAGE: ${{ needs.check-event.outputs.package }}
        run: python3 .github/scripts/package_plugin.py
      - name: Upload Source Tarball 🗜️
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-${{ matrix.os }}-sources-${{ needs.check-event.outputs.commitHash }}
          path: ${{ github.workspace }}/release/${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-source.*
      - name: Upload Artifacts 📡
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-${{ matrix.os }}-x86_64-${{ needs.check-event.outputs.commitHash }}
          path: ${{ github.workspace }}/release/${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-x86_64*.*
  windows-build:
    name: Build for Windows 🪟
    runs-on: windows-2022
    needs: check-event
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set Up Environment 🔧
        id: setup
        run: python .github/scripts/setup_env.py
      - name: Set Up Rust 🦀
        run: python .github/scripts/setup_rust.py
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            ~/.cargo/git/db
            ${{ github.workspace }}/target
          key: ${{ runner.os }}-windows-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: ${{ runner.os }}-windows-cargo-
      - uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/.deps
          key: ${{ runner.os }}-windows-deps-${{ hashFiles('buildspec.json') }}
      - name: Build Plugin 🧱
        run: python .github/scripts/build_plugin.py
      - name: Package Plugin 📀
        env:
          PACKAGE: ${{ needs.check-event.outputs.package }}
        run: python .github/scripts/package_plugin.py
      - name: Upload Artifacts 📡
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-windows-x64-${{ needs.check-event.outputs.commitHash }}
          path: ${{ github.workspace }}/release/${{ steps.setup.outputs.pluginName }}-${{ steps.setup.outputs.pluginVersion }}-windows-x64*.*
  create-release:
    name: Create Release 🛫
    if: github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    needs: [check-event, macos-build, ubuntu-build, windows-build]
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - name: Check Release Tag ☑️
        id: check
        run: python3 .github/scripts/check_release_tag.py
      - name: Download Build Artifacts 📥
        uses: actions/download-artifact@v4
        if: fromJSON(steps.check.outputs.validTag)
        id: download
      - name: Collect Release Assets 🏷️
        if: fromJSON(steps.check.outputs.validTag)
        run: python3 .github/scripts/release_assets.py
      - name: Create Release 🛫
        if: fromJSON(steps.check.outputs.validTag)
        id: create_release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
        with:
          draft: false
          tag_name: ${{ steps.check.outputs.version }}
          name: ${{ needs.check-event.outputs.pluginName }} ${{ steps.check.outputs.version }}
          body_path: ${{ github.workspace }}/CHECKSUMS.txt
          files: |
            ${{ github.workspace }}/*.exe
            ${{ github.workspace }}/*.zip
            ${{ github.workspace }}/*.pkg
            ${{ github.workspace }}/*.deb
            ${{ github.workspace }}/*.tar.xz
