name: Check Code Formatting 🛠️
on:
  workflow_call:
jobs:
  rustfmt:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Up Rust 🦀
        run: python3 .github/scripts/setup_rust.py
      - name: rustfmt check 🦀
        run: cargo fmt --check
  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set Up Environment 🔧
        run: python3 .github/scripts/setup_env.py
      - name: Set Up Rust 🦀
        run: python3 .github/scripts/setup_rust.py
      - name: clippy check 🦀
        run: cargo clippy --all-targets -- --deny warnings
